### ISSUE TITLE
Use std::hypot(x, y) Instead Of std::sqrt(x * x, y * y)

### ISSUE THREAD

**Issue by ldo** [yuki-koyama/color-util#23]
I notice you use `std::sqrt(`_x_ `*` _x_, _y_ `*` _y_`)` a lot. It is better to use [`std::hypot`](https://en.cppreference.com/w/cpp/numeric/math/hypot) instead, and just write `std::hypot(`_x_, _y_`)`.

**Comment by yuki-koyama** [comment]
Thank you, I haven't been aware of that function. This suggestion is very helpful!

**Comment by yuki-koyama** [comment]
I learned that `std::hypot` is significantly slower than the naive approach, while it can avoid overflow and underflow for large and small arguments, respectively. I would like to keep the naive approach for the following reasons.
- The library currently uses the naive approach for the CIEDE2000 function, whose arguments are Lab values. Lab values will never be very large and are unlikely to be very small (considering typical display and camera sensor resolutions).
- It is beneficial to keep the CIEDE2000 function as efficient as possible since it is sometimes called many times (e.g., evaluating the color differences of every pair of pixels in a large image).

Again, thank you for the suggestion!
